language: go
os:
- linux
before_install:
- git clone https://github.com/bukalapak/snowboard.git $GOPATH/src/github.com/bukalapak/snowboard
- make -C $GOPATH/src/github.com/bukalapak/snowboard install
script:
- go test -v ./
